### PR TITLE
Added toString method for converting JEXL to expression string

### PR DESCRIPTION
**Pull request by cosmos-lab**
HI @astephens25 
Details of the changes in this PR:

**Problem**
Existing library **chetbox/jexl-to-string** doesn't support spaces in object keys.

**Intent of this PR**
Provide a method for converting an AST to an Expression String.

**Approach**
I have copied and pasted chetbox/jexl-to-string in to a file **lib/serialize.js** and applied the fix on the top of that to support spaces in object keys.

I added new test cases inside **__tests__/lib/serialize.test.js** 

Added a member function **toString** inside the **Jexl** class **lib/Jexl.js**, which utilise **jexlExpressionStringFromAst** method imported from **serialize.js**

**Key Points to Review**
**toString** method inside the **Jexl** class
New files added **lib/serialize.js** and **__tests__/lib/serialize.test.js** 

Thanks

### CODE REVIEW

**Comment by astephens25** [comment]
@cosmos-lab Please provide a complete description of your intent, approach, and any key points for review.

**Comment by astephens25** [comment]
This is a good idea, but the implementation is not correct. Adding a `toString` method to the base object and expecting the AST to be passed in might as well be a separate project or function altogether. This is not the approach I wish to take.

There is not attribution for the work of Chetan Padia in creating this string conversion library. Whenever copying someone's code, attribution is critical under the MIT license. 

I will re-implement this and release an update to the the @firehammer/jexl package soon.

**Comment by cosmos-lab** [comment]
For your information, the implementation is as per your guidance. My solution was entirely different and re-implemented but you have rejected! Because I've re-written the string conversion library. You suggested me to put a PR with the minimal changes to reduce the testing effort. I would suggest you to revert my changes because even I am not satisfied with the changes.

**Comment by cosmos-lab** [comment]
@astephens25 

I was considering addressing this issue in a different way, but I followed your advice from our offline conversation, which was valid. 
To avoid any confusion, I want to clarify that the missing attribution for Chetan Padia’s valuable work was unintentional. Since you recommended including Chetan's work and you are the subject matter expert on this solution, I was seeking further guidance from you before finalizing the draft of the PR and adding the proper attribution. I was seeking the appropriate place to include it and was simply validating the initial solution.

I saw that you added attribution nicely in the README. I liked it. 

Thanks for the feedback. Enjoy coding!

**Comment by cosmos-lab** [comment]
@astephens25 

First thing:
The attribution for this work is not included either  https://github.com/chetbox/jexl-to-string/pull/3

Second thing:
And you simply copied "my" solution from this PR https://github.com/chetbox/jexl-to-string/pull/4 
Commit: https://github.com/firehammersolutions/jexl/commit/1b41f1b57840cbf4d5ff254485b9c0fbacfe687c#diff-0b54a0fe4e28dd7c969fecd6711539ca19dcd5cc1e19a175193d805468d863caR116

_Just kidding_. 

Since you flat-out copied and pasted and there is no reference to the commit left, I'm adding the PR URL for reference because I keep forgetting what changes I made to handle "large numbers" and "sustain space in a key".

Thanks

**Pull request closed without merging**
